# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Session-Plugin-Redirect
version:      1.00
version_from: lib/CGI/Session/Plugin/Redirect.pm
installdirs:  site
requires:
    CGI::Session:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
